# Generated by Django 2.1.5 on 2019-01-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190130_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
